#Python 3.8.2
##############################
#
#   Zepazo.py
#
##############################

import  argparse
from Analyzers.video_utilities import VideoAnalyzer
from sys import argv
from pathlib import Path
import os
import json


#################
#
#   Arguments
#
#################
#Needed to Sphinx
ARGS_DOCS = ['-v', '../videos/test.mp4']

parser = argparse.ArgumentParser(description="Zepazo: Get moon impacts frames")
parser.add_argument( "-v", "--video", type=str, help="Video file path to analize")
parser.add_argument( "-d", "--debug", help="Show video during analysis", action='store_true')
parser.add_argument( "-mm", "--mousemask", type=int, help="Place num_masks rectangular masks  by clicking in first frame ")
parser.add_argument( "-cm", "--coordinatesmask",nargs='+', type=int, help="Place num_masks rectangular masks  by giving a list of points")
parser.add_argument( "-l", "--detectionlimit", type=int, help="Detection limit (1-255) Default 50")
parser.add_argument( "-cl", "--circlelimit", type=int, help="Moon contour detection limit (1-255) Default ~33 calculated while analysis")
parser.add_argument( "-f", "--folder", type=str, help="Folder path to save impacts")
parser.add_argument( "-ssf", "--saveSurroundingFrames", type=int, help="Save n frames before and after each detection")
parser.add_argument( "-dt", "--dilate", type=int, help="Dilate previous images to avoid clear parts of the moon due to movement")
parser.add_argument( "-cf", "--configFile", type=str, help="JSON file generated by the interface")

if ( Path(argv[0]).name != 'sphinx-build' ):
    args = parser.parse_args()
else:
    args = parser.parse_args(ARGS_DOCS)

#CHECK ERRORS
if(args.detectionlimit != None):
    if(args.detectionlimit < 1 or args.detectionlimit > 255):
        parser.error("Detection limit (-l) must be between 1 and 255")

if(args.video == None):
        parser.error("Video (-v) must be defined")

if(args.folder !=None and os.path.exists(args.folder) == False):
    parser.error("Folder (-f) must exists")

if(args.saveSurroundingFrames != None and args.saveSurroundingFrames < 0):
    parser.error("Surrounding farmes (-ssf) must be a possitive number")

if(args.configFile != None and os.path.exists(args.configFile) == False):
    parser.error("Config file (-cf) must exists")

#CHECK IF JSON FILES IS GIVEN
video = args.video
print(video)
debug = args.debug

if(args.configFile == None):
    detectionlimit = args.detectionlimit
    circlelimit = args.circlelimit
    mousemask = args.mousemask
    folder = args.folder
    saveSurroundingFrames = args.saveSurroundingFrames
    dilate = args.dilate
else:
    with open(args.configFile, 'r') as json_file:
        jsonFile = json.load(json_file)
    
    detectionlimit = jsonFile["detectionlimit"]
    circlelimit = jsonFile["circlelimit"]
    mousemask = jsonFile["coordinatesmask"]
    folder = jsonFile["folder"]
    saveSurroundingFrames = jsonFile["saveSurroundingFrames"]
    dilate = jsonFile["dilate"]
#################
#
#  Program
#
#################
video_analizer = VideoAnalyzer(video, debug, detectionlimit, circlelimit, mousemask, folder, saveSurroundingFrames, dilate)

#Pre Processing
# -> Apply a mask
if(args.mousemask != None):
    video_analizer.selectAndApplyMask(args.mousemask)
else:
    if(args.coordinatesmask != None):
        if(len(args.coordinatesmask) % 2 != 0):
            parser.error("Coordinate list must be even")
        else:
            video_analizer.selectAndApplyMask(len(args.coordinatesmask), args.coordinatesmask)


#Proccessing
video_analizer.analyze(None,None)