name: 'Unit tests'
on: [push]

jobs:
  build_container_and_run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker container
      run: xvfb-run && docker build . -t zepazo && docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix zepazo